import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`flex flex-col ${inter.className}`}>
        <header className={"sticky top-0"}>
            <nav className={"flex justify-between items-center p-4"}>
                {/*TODO MUNGKIN NNTI GANTI LOGO*/}
                {/*TODO NNTI STYLE*/}
                <h1>Pokedex</h1>
                <ul className={"flex list-none gap-4"}>
                    <li >
                        <a href="#">Home</a>
                    </li>
                    <li>
                        <a href="#">Compare</a>
                    </li>
                </ul>
            </nav>
        </header>
        <main className={"grow p-4"}>
            {children}
        </main>
      </body>
    </html>
  );
}
